### ISSUE TITLE
Expected battery life?

### ISSUE THREAD

**Issue by MACscr** [EasySensors/SwitchNode#1]
I just want to connect a switch to it and when the switch is toggled one way or another, it sends a packet to my HomeAssistant server which is equipped with an 433mhz RF Bridge. Should be pretty simple and should sit dormant most of the time.

**Comment by yurysvirida** [comment]
Hi,

Roughly  4.69 years if one switch pressed once an hour.
calculator  http://oregonembedded.com/batterycalc.htm  

If JDEC eprom soldered for FOTA\OTA .  Drain current 4uA( all switches OFF ) - 8uA (one switch is on).  

You need to send JDEC to sleep explicitly. otherwise JDEC will eat 10 uA extra.

If no need JDEC it is 3uA less of the drain current, means overall drain will be close to 1uA.  
 
![image](https://user-images.githubusercontent.com/18707133/34559089-3f638d38-f149-11e7-9e20-bffcb2be42df.png)
![image](https://user-images.githubusercontent.com/18707133/34560488-90dfe706-f14e-11e7-884b-b91e6daa70bd.png)


Hope I described it clear...
